[Output]
ImageId=hod-arch
Format=disk
Bootable=yes
Bootloader=grub
BiosBootloader=grub
KernelCommandLine=root=LABEL=hod rw
OutputDirectory=.hod-vm/arch

[Distribution]
Distribution=arch

[Content]
Packages=base,linux,systemd,openssh,ttf-dejavu,dracut
WithDocs=no

[Partition]
RootSize=8G
ESPSize=512M
