//! containers-config — static configuration files for podman/containers.
//!
//! Generates configuration files that don't depend on store paths:
//!   - registries.conf — default container registries (docker.io)
//!   - policy.json — default image verification policy
//!
//! Runtime configuration (containers.conf, storage.conf) is generated by
//! the podman wrapper script, which discovers helper binary paths from
//! the Hod staging layout at runtime.

import { shellBuild, dep, importToStore } from "../../../js/src/index.js";
import { nativeToolchainRecipe } from "../../toolchain/native-toolchain.js";
import { cProfile } from "../../helpers/c.js";

const recipe = await shellBuild({
  ...cProfile(),
  script: `
mkdir -p $OUT/etc/containers

cat > $OUT/etc/containers/registries.conf << 'EOF'
[registries.search]
registries = ['docker.io']

[registries.insecure]
registries = []

[registries.block]
registries = []
EOF

cat > $OUT/etc/containers/policy.json << 'EOF'
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ]
}
EOF
`,
  deps: [
    dep("toolchain", nativeToolchainRecipe),
  ],
});

await importToStore(recipe);
export const containersConfigRecipe = recipe;
